// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRx72udLOI5y021k2SlClenlyA3_HfA0',
    appId: '1:144659314794:web:bbcae1b78fcdb6c1b1b213',
    messagingSenderId: '144659314794',
    projectId: 'auth-muscle-v2',
    authDomain: 'auth-muscle-v2.firebaseapp.com',
    storageBucket: 'auth-muscle-v2.firebasestorage.app',
    measurementId: 'G-T0C940ZL5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhu0QPWjT57cd_TWfAkQ0umfoXqVAjfn4',
    appId: '1:144659314794:android:13287c41bf504ea6b1b213',
    messagingSenderId: '144659314794',
    projectId: 'auth-muscle-v2',
    storageBucket: 'auth-muscle-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1i0OTTdwK6sHcJQfEOBgMcOZ4Va8wy9k',
    appId: '1:144659314794:ios:f5c50aa529ef5a1bb1b213',
    messagingSenderId: '144659314794',
    projectId: 'auth-muscle-v2',
    storageBucket: 'auth-muscle-v2.firebasestorage.app',
    iosBundleId: 'com.example.authMuscleV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1i0OTTdwK6sHcJQfEOBgMcOZ4Va8wy9k',
    appId: '1:144659314794:ios:f5c50aa529ef5a1bb1b213',
    messagingSenderId: '144659314794',
    projectId: 'auth-muscle-v2',
    storageBucket: 'auth-muscle-v2.firebasestorage.app',
    iosBundleId: 'com.example.authMuscleV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFRx72udLOI5y021k2SlClenlyA3_HfA0',
    appId: '1:144659314794:web:172c02d3f7b59df6b1b213',
    messagingSenderId: '144659314794',
    projectId: 'auth-muscle-v2',
    authDomain: 'auth-muscle-v2.firebaseapp.com',
    storageBucket: 'auth-muscle-v2.firebasestorage.app',
    measurementId: 'G-2GN7Z5S6EH',
  );

}